bookstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('coupons/', include('coupons.urls')),
    path('',include('users.urls')),
    path('',include('bookshop.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('payment.urls')),
   
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from bookshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart_detail')


def cart_detail(request):
  
        
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/cart_detail.html', {'cart': cart,'coupon_apply_form':coupon_apply_form})

cart/templates/cart/cart_detail.html
{% extends 'bookshop/base.html' %}
{% load static %}
<title>{% block title %} Cart Details | Bookshop {% endblock%}</title>
{% block content %} 
    <div class="ps-hero">
        <div class="container">
            <h3>YOUR CART</h3>
            <p>Page Cart</p>
        </div>
    </div>
    

   
    <div class="ps-content pt-80 pb-80">
        <div class="ps-container">
            <div class="ps-cart-listing">
                <table class="table ps-cart__table">
                    <thead>
                        <tr>
                            <th>All Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for item in cart %}
                            {% with product=item.product %}
                                <tr>
                                    <td><a class="ps-product--compare" href="{{ product.get_absolute_url }}">
                                        <img class="mr-15" src="{% if product.image %}{{ product.image.url }}
                                        {% else %}{% static 'img/no_image.png' %}{% endif %}" alt="">
                                        {{ product.name }}</a></td>
                                    <td>${{ item.price }}</td>
                                    <td>
                                        <div class="form-group--number">
                                            <form action="{% url 'cart_add' product.id %}" method="post">
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.override }}
                                                <input type="submit"  value="+" style="background-color: black; color:white;">
                                                {% csrf_token %}
                                              </form>
                                           
                                            
                                        </div>
                                    </td>
                                    <td>${{ item.total_price }}</td>
                                    <td>
                                        <form action="{% url 'cart_remove' product.id %}" method="post">
                                            <button class="ps-remove"></button>
                                            {% csrf_token %}
                                          </form>
                                        
                                    </td>
                                </tr>
                            {% endwith %}
                        {% endfor %}
                       
                    </tbody>
                </table>
                <div class="ps-cart__actions">
                    <div class="ps-cart__promotion">
                        <div class="form-group">
                            <div class="ps-form--icon">
                               
                                <form action="{% url 'coupons:apply' %}" method="post">
                                    
                                     <input class="form-control" name="coupon" type="text" placeholder="Promo Code">
                                    {% csrf_token %}
                                </form>
                            </div>
                        </div>
                        <div class="form-group">
                            <a href="{% url 'product_list' %}"><button class="ps-btn ps-btn--gray">Continue Shopping</button></a>
                        </div>
                    </div>
                    <div class="ps-cart__total">
                        {% if cart.coupon %}
                            
                                <h3>Subtotal <span>${{ cart.get_total_price|floatformat:2 }}</span></h3>
                                <h3>"{{ cart.coupon.code }}" coupon
                                    ({{ cart.coupon.discount }}% off)<span style="color: red;">- ${{ cart.get_discount|floatformat:2 }}</span></h3>

                        {% endif %}
                        <h3>Total Price: <span> ${{ cart.get_total_price_after_discount|floatformat:2 }}</span></h3>

                        {% if cart.get_total_price == 0 %}
                        <button class="ps-btn" >Cart is Empty</button>
                        {% else %}
                            <a class="ps-btn" href="{% url 'order_create' %}">Process to checkout</a>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
                
{% endblock %}